# Ajustes SO
# https://hub.docker.com/_/sonarqube

version: "3.8"
services:
    sonarqube:
        image: sonarqube:8-community
        depends_on:
            - database
        ports:
            - 9000:9000
        networks:
            - docker-network
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://database:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        volumes:
            - sonarqube_data:/opt/sonarqube/data

    database:
        image: postgres
        networks:
            - docker-network
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - postgresql_data:/var/lib/postgresql/data

networks:
    docker-network:
        driver: bridge

volumes:
    sonarqube_data:
    postgresql_data:
