name: Build and deploy ASP.Net Core app to Azure Web App - onetimepassword

on:
  push:
    branches: master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Zip Package
        cd ${{env.DOTNET_ROOT}}/myapp
        zip -r ${{env.DOTNET_ROOT}}/myapp/out.zip

    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
        region: sa-east-1
        application_name: OneTimePassword
        environment_name: Onetimepassword-env-1
        version_label: ${{github.run_id}}
        version_description: ${{github.sha}}
        deployment_package: ${{env.DOTNET_ROOT}}/myapp/out.zip
